apiVersion: apps/v1
kind: Deployment
metadata:
  name: iwallet-app-blue
  namespace: iwallet-app
  
spec:
  replicas: 5
  selector:
    matchLabels:
      app: iwallet-app
  template:
    metadata:
      labels:
        app: iwallet-app
        version: blue
    spec:
      imagePullSecrets: 
        - name: ghcr-secret
      containers:
        - name: iwallet-app-container
          image: ghcr.io/abobkeryousif/iwallet:1afc2df3b6a05ebaa22b4fa54c31c1e920380737
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "300Mi" 
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "350m"
